package com.reminder.constants.enums;

public enum ExpenseCategories {
    HOUSING,
    TRANSPORTATION,
    FOOD,
    HEALTH_AND_MEDICAL,
    INSURANCE,
    DEBT_PAYMENTS,
    ENTERTAINMENT_AND_RECREATION,
    PERSONAL_CARE,
    EDUCATION,
    FAMILY_AND_CHILDCARE,
    SAVINGS_AND_INVESTMENTS,
    DONATIONS_AND_GIFTS,
    TAXES,
    MISCELLANEOUS;
}
